project:
  type: website

website:
  title: "📦 Fundamentals of R Package Development"
  navbar:
    background: secondary
    right:
      - icon: github
        href: https://github.com/ateucher/pkg-dev-workshop
        aria-label: GitHub
  repo-url: https://github.com/ateucher/pkg-dev-workshop
  repo-actions: [edit, issue]
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: "Basics"
        contents:
          - intro.qmd
          - setup.qmd
          - understanding-pkgs.qmd
      - section: "The Whole Game"
        contents:
          - create-check.qmd
          - description.qmd
          - r-code.qmd
          - documentation.qmd
          - test.qmd
          - check.qmd
      - href: dependencies.qmd
      - href: ci.qmd
      - href: share.qmd
      - href: website.qmd

format:
  html:
    theme:
      light:
        - flatly
        - style-light.scss
      dark:
        - darkly
        - style-dark.scss
    toc: true



